//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flat()
        {
            this.pictures = new HashSet<picture>();
            this.requestFlats = new HashSet<requestFlat>();
        }
    
        public int flatId { get; set; }
        public string adress { get; set; }
        public Nullable<double> longtitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<int> numBeds { get; set; }
        public Nullable<int> numRooms { get; set; }
        public Nullable<int> numFloor { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> flatOwnerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<picture> pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requestFlat> requestFlats { get; set; }
    }
}
