//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int pictureId { get; set; }
        public Nullable<int> flatId { get; set; }
        public string pathToFile { get; set; }
    
        public virtual flat flat { get; set; }
    }
}
